#
# Project: robotlegs-utilities-macrobot
#
# Author:  Alessandro Bianco
# Website: http://alessandrobianco.eu
# Twitter: @alebianco
# Created: 18/10/2014 23.12
#

language: objective-c

git:
  depth: 1

env:
  - TERM=dumb

deploy:
  provider: releases
  api-key:
    secure: "iOHRj8qngFQe67OJ9DcJVvSlf/9qI+rySL9BX1fr/yF3/n1qCmengC90h76DfreU7ZfmTj8vyzVrfEDWQeZPUeOeAQVON1XwktUDY2LfsjAfgsuJXzwYzx4pPBAF8I6nWlaC0ta1vr+irIbZ8sRY2lS/vZY6Oeo0mreWbIKOKck="
  file: "release/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

before_install:
  - brew update >brew-update.log
  - chmod +x gradlew

install:
  - brew install caskroom/cask/brew-cask
  - brew cask install flash-player-debugger

before_script:
  - export FLASH_PLAYER_EXE="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"

script: ./gradlew release